### ISSUE TITLE
Duplicated key

### ISSUE THREAD

**Issue by moissinac** [scienceai/web-verse#21]
I'm thinking web-verse could be very useful.
I'm doing some try with web-verse and think that good practices and strategies are necessary
It is very easy to imagine documents with some repetitive content . For exemple, a document which compare several softwares can have the following element 'Advantages of the tool are listed in the following paragraphs'  (key AotAot). So, each occurence of the element will get the same key.

In my trial with a mid-long document, I get 188 unique keys for 590 elements (with a frequent special case of empty elements and a lot of small elements). By changing what is viewed as an element, I can go to about 5% to 10% of duplicated keys, but never only unique keys. So, I think I need to supervise my process by segmenting the document and to combine a reference to a segment then a key.
Is there  some advices to get the best of web-verse?

**Comment by sballesteros** [comment]
The [video](http://2014.jsconf.eu/speakers/michael-donohoe-deeplink-to-anything-on-the-web.html) listed in the README is probably the best entry point.
